// == Is equals to operator is a comarison operator between two data types 
// = is a an assignment operator 
#include <iostream>
using namespace std;
int main() {
    int x=3;
    cout << ((x==3));
}
// output will be 1 because x is equal to 3 and the condition is true. If we change the value of x to something other than 3, the output will be 0 because the condition will be false.
// thats the diff between == and  = operatore 