#include <iostream>
using namespace std;
 int main() {
    // increment and decrement operator 
    // idk what to write here 

   int x=5;
   cout<<x<<endl;
  //  ++x; // pre incrment --> x=x+1
  //  cout<<x<<endl;
  //  x++; //post increment 
  //  cout<<x<<endl;
  //  x--; //x =x-1
  //  cout<<x<<endl;
  //  --x; // x=x-1
  //  cout<<x<<endl;
   cout<<--x<<endl;
   cout<<x--<<endl;
   cout<<x<<endl;
   return 0;
 }